# Uncomment and configure if this project accepts sponsorships.
# See https://docs.github.com/en/repository-nav/customizing-your-repository/displaying-a-sponsor-button-in-your-repository
#
# github: [itsbabluthakur]
# open_collective: reviewflow-ai
# custom: ["https://example.com/donate"]
